services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_DB: speciesdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d speciesdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://user:password@db:5432/speciesdb
      JWT_SECRET_KEY: super-secret-key
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend